### PR TITLE
Ui

### PR DESCRIPTION
**Pull request by ashley7295**
Here is some code we worked on together in our group Zoom meeting. I added a lot fo TODO's in here for once we get everything merged, but currently its a good foundation for getting all of our code together and getting it to do something collectively.
@yp0975eu 
@jy8474np 
@Issemoh

### CODE REVIEW

**Review by yp0975eu — APPROVED** [review]
This looks like a good start for ui. We will still need unit tests and api integrations.

**Comment by yp0975eu** [comment]
I've resolved the conflicts in main. We will need to integrate Spotify search a little better

**Comment by jy8474np** [comment]
UI in progress with group suggestions integration and integral file merging as goal.

**Review by jy8474np — APPROVED** [review]
Reviewed. Looks good - Conflicts and updates discussed in 10/22 and 10/26 Zoom code review sessions.

**Review by Issemoh — APPROVED** [review]

**Pull request merged**
