### PR TITLE
Lyrics/apiseeds

### PR DESCRIPTION
**Pull request by yp0975eu**

### CODE REVIEW

**Comment by yp0975eu** [comment]
TODO: Add unit test for this.

**Comment by ashley7295** [comment]
Notes from in person code review: 
-adjusted call_service to be notated as a private method as "__call_service"
-CON of using this API, API does not contain a large database of artists and lyrics
-can add more printing code in get_lyrics
-add validation in get_lyrics?
-needs tests
-needs caching

**Comment by jy8474np** [comment]
Zoom code review. Create a standard for displaying lyrics? How to validate for lyrics/artist search? Cacheing to be added after resolution. Code needs testing/validation.

**Comment by ashley7295** [comment]
I'm okay to merge this code into master if you are feeling good about it! I think what we looked at together during class time looks great.

**Review by ashley7295 — APPROVED** [review]
API looks good for retrieving lyrics!

**Review by jy8474np — APPROVED** [review]

**Comment by jy8474np** [comment]
Accidentally approved without comment. Comment: Good progress on updates discussed in 10/22 and 10/26 Zoom code review sessions. Pending pieces completed my other team members (us).

**Review by Issemoh — APPROVED** [review]

**Pull request merged**
